name: Slack Notification
description: send slack alert about build
inputs:
  SLACK_WEBHOOK:
    required: true
    description: Slack Webhook Token
  SLACK_SUCCESS_MESSAGE:
    required: true
    description: Message for slack body
runs:
  using: 'composite'
  steps:
    - name: Set SLACK_MESSAGE
      run: |
         [[ ${{ job.status }} == success ]] && echo "SLACK_MESSAGE=${{ inputs.SLACK_SUCCESS_MESSAGE }} >> $GITHUB_ENV \
                || echo "SLACK_MESSAGE=:red_circle: A Build Docker Image job has failed!" >> $GITHUB_ENV
      shell: bash
    - name: Slack success alert
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: es-test
        SLACK_COLOR: ${{ job.status }}
        SLACK_USERNAME: GitHub Action Releases
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
        SLACK_TITLE: 'Project: ${{ env.REPO_NAME }}'
        MSG_MINIMAL: actions url,commit
        # SLACK_MESSAGE: ${{ inputs.SLACK_SUCCESS_MESSAGE }}