executors:
  node:
    docker:
      - image: cimg/node:14.17

version: 2.1

workflows:
  Test:
    jobs:
      - Test

jobs:
  Test:
    executor: node
    environment:
      VERSION_NUMBER: ${CIRCLE_TAG%"-ios"}
      #BUILD_NUMBER:
    steps:
      - run:
          name: Echo var
          command: echo $VERSION_NUMBER