executors:
  node:
    docker:
      - image: cimg/node:14.17

version: 2.1

workflows:
  Test:
    jobs:
      - Test

jobs:
  Test:
    executor: node
    environment:
      CIRCLE_TAG: "7.22.7-ios"
      VERSION_NUMBER: $(echo "${CIRCLE_TAG}" | awk -F "-" '{print $1}')
      #BUILD_NUMBER:
    steps:
      - run:
          name: Echo var
          command: echo $VERSION_NUMBER