name: Build and Upload IOS app - Production

on:
  push:
    #  tags:
    #    - "[0-9]+.[0-9]+.[0-9]+\\+ios"

env:
  GIT_TAG: 1.0.0+ios #${{ github.ref_name }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
   build_and_upload:
      name: Build and Upload IOS app - Production
      runs-on: macos-11
      steps:
        - name: Update Version Number & Build Number
          run: |
            echo "VERSION_NUMBER=${GIT_TAG/+*}" >> $GITHUB_ENV
            echo "BUILD_NUMBER=$(date +%y%m%d%H)" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        - run: echo $GIT_TAG - $VERSION_NUMBER - $BUILD_NUMBER
        - name: Set up Ruby env
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.1
            bundler-cache: true
        - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
             key: ${{ secrets.SSH_KEY }}
             known_hosts: ${{ secrets.KNOWN_HOSTS }}
        - name: Check
          run: bundle exec fastlane ios test
          env:
             MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        # - name: Use node.js 14
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: '14'
        #     registry-url: 'https://registry.npmjs.org'
        #   env:
        #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        # - name: Cache Modules
        #   uses: actions/cache@v2
        #   with:
        #     path: '**/node_modules'
        #     key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
        # - name: Install Dependencies
        #   run: npm install --no-audit
        # - name: Build Production Mobile sources
        #   run: npm run build:production:mobile
        #   env:
        #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        # - name: Sync Android
        #   run: npx cap sync android
        # - name: Decode Keystore & API Playstore Key files
        #   run: |
        #     echo ${{ secrets.ANDROID_KEYSTORE }} | base64 -d | tee android-keystore.jks android/app/android-keystore.jks
        #     echo ${{ secrets.API_PLAYSTORE_KEY }} | base64 -d | tee android/api-play-store-key.json
        # - name: Build and Upload Bundle (.aab) to GooglePlayStore Beta-Open Testing
        #   run: bundle exec fastlane android build_aab
        #   env:
        #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        #     SLACK_URL: ${{ secrets.SLACK_WEBHOOK }}
