name: Build Production Docker image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-tests"

env:
  GIT_TAG: ${{ github.ref_name }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
            
  test_job:
     name: Tests
     runs-on: ubuntu-20.04
     steps:
        - name: Check git tag
          run: echo ${{ env.GIT_TAG }}