name: Build and Upload Android app - stage

on:
  push:
    # tags:
    #   - "[0-9]+.[0-9]+.[0-9]+-tests"

# env:
#   GIT_TAG: ${{ github.ref_name }}
#   REPO_NAME: ${{ github.event.repository.name }}

jobs:
   build_and_upload:
      name: Build and Upload Android app - stage
      runs-on: ubuntu-20.04
      env:
        VERSION_NUMBER: ${{ github.ref_name }}
        BUILD_NUMBER: date '+%y%m%d%H'
      steps:
        - name: List Version Number & Build Number
          run: echo $VERSION_NUMBER ${{ fromJSON($BUILD_NUMBER) }}