name: Build Production Docker image

on: push
    # tags:
    #   - "[0-9]+.[0-9]+.[0-9]+-tests"

env:
  GIT_TAG: ${{ github.ref_name }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
   build:
     name: Build Docker image
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v3
       - name: Use node.js 14
         uses: actions/setup-node@v3
         with:
           node-version: '14'
        #    registry-url: 'https://registry.npmjs.org'
        #  env:
        #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
       - name: Copy .npmrc to HOME directory
         run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
         env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
       - run: cat $HOME/.npmrc
      #  - name: Configure AWS credentials
      #    uses: aws-actions/configure-aws-credentials@v1
      #    with:
      #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #      aws-region: us-east-1
      #  - name: Build docker image for service
      #    run: ./scripts/build.sh events $GIT_TAG false
        #  env:
    #    - uses: ./.github/actions/slack-alert
    #      if: always()
    #      with:
    #        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #        SLACK_SUCCESS_MESSAGE: "📦 Docker image *${{ env.REPO_NAME }}@${{ env.GIT_TAG }}* created! (by ${{ github.actor }})!"
